"""
design/tokens.json -> CSS custom properties and Dart constants.

    python tools/tokens.py            write both exports
    python tools/tokens.py --check    fail if either is stale, write nothing

WHY A BUILD STEP AND NOT TWO HAND-KEPT FILES
--------------------------------------------
Product brief 2.6. Two clients shipping in parallel drift the moment a hex
value exists in two places, and the brief calls a colour that differs between
web and native a bug rather than an inconsistency. Acceptance criterion 10 is
that a token change in the shared source updates both.

--check is what makes that real: tests/test_tokens.py runs it, so a token
edited in the source and not exported is a test failure, not a visual surprise
noticed three screens later.

THE GENERATED FILES ARE NOT EDITED. Both carry a header saying so and naming
this script. That is the only defence against somebody fixing a colour in the
CSS, which then silently disagrees with Dart until a screenshot catches it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
CSS_OUT = ROOT / "bpcad" / "web" / "static" / "tokens.css"
DART_OUT = ROOT / "mobile" / "lib" / "tokens.dart"

BANNER = "GENERATED FROM design/tokens.json - DO NOT EDIT THIS FILE"
REGENERATE = "Change the token there and run: python tools/tokens.py"


def load() -> dict[str, Any]:
    if not SOURCE.is_file():
        raise SystemExit("no token source at %s" % SOURCE)
    return json.loads(SOURCE.read_text())


def _clean(section: dict[str, Any]) -> dict[str, Any]:
    """Drop the $comment keys; they document the source, not the output."""
    return {k: v for k, v in section.items() if not k.startswith("$")}


def _hexes(section: dict[str, Any]) -> dict[str, str]:
    return {k: v["hex"] for k, v in _clean(section).items()}


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

def to_css(tokens: dict[str, Any]) -> str:
    lines = [
        "/*",
        " * %s" % BANNER,
        " * %s" % REGENERATE,
        " *",
        " * Product brief 6.1: the core palette is six values and the pen set is",
        " * used ONLY inside the 3D canvas and for annotation. A pen colour on",
        " * chrome is a bug, and so is a hex literal anywhere else in the CSS.",
        " */",
        "",
        ":root {",
    ]

    lines.append("  /* core palette */")
    core = _clean(tokens["core"])
    pad = max(len(n) for n in core) + len("  --bp-: #000000;")
    for name, value in core.items():
        declaration = "  --bp-%s: %s;" % (name, value["hex"])
        lines.append("%-*s /* %s */" % (pad, declaration, value["use"]))

    lines.append("")
    lines.append("  /* viewport pen set - canvas and annotation only */")
    pens = _clean(tokens["pen"])
    pad = max(len(n) for n in pens) + len("  --bp-pen-: #000000;")
    for name, value in pens.items():
        declaration = "  --bp-pen-%s: %s;" % (name, value["hex"])
        lines.append("%-*s /* %s */" % (pad, declaration, value["meaning"]))

    lines.append("")
    lines.append("  /* type */")
    lines.append("  --bp-mono: %s;" % tokens["type"]["mono"]["stack"])
    lines.append("  --bp-prose: %s;" % tokens["type"]["prose"]["stack"])
    for name, size in _clean(tokens["type"]["scale"]).items():
        lines.append("  --bp-text-%s: %gpx;" % (name, size))
    for name, weight in _clean(tokens["type"]["weight"]).items():
        lines.append("  --bp-weight-%s: %d;" % (name, weight))

    lines.append("")
    lines.append("  /* spacing */")
    for name, size in _clean(tokens["space"]).items():
        lines.append("  --bp-space-%s: %gpx;" % (name, size))

    lines.append("")
    lines.append("  /* radii */")
    for name, size in _clean(tokens["radius"]).items():
        lines.append("  --bp-radius-%s: %gpx;" % (name, size))

    lines.append("")
    lines.append("  /* pinned metrics */")
    for name, size in _clean(tokens["metric"]).items():
        lines.append("  --bp-%s: %gpx;" % (name.replace("_", "-"), size))

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Dart
# ---------------------------------------------------------------------------

def _dart_colour(hex_value: str) -> str:
    return "Color(0xFF%s)" % hex_value.lstrip("#").upper()


# DART RESERVED WORDS THAT COLLIDE WITH TOKEN NAMES.
#
# The brief's first colour is called `case` - the machine's shell - and `case`
# is a Dart keyword, so the generated file would not compile. Caught by
# generating it rather than by reading it, which is the argument for the build
# step existing at all.
#
# Renaming the token in the source would be worse: the name comes from the
# brief and web keeps it. So the Dart identifier gains a suffix and says why,
# and the mapping is written here rather than special-cased at the call site.
DART_RESERVED = {
    "case": "caseColor",
    "class": "classColor",
    "default": "defaultValue",
    "in": "inValue",
    "is": "isValue",
    "new": "newValue",
    "null": "nullValue",
    "switch": "switchValue",
    "this": "thisValue",
    "var": "varValue",
    "void": "voidValue",
    "with": "withValue",
    "final": "finalValue",
    "const": "constValue",
    "static": "staticValue",
    "enum": "enumValue",
    "extends": "extendsValue",
    "super": "superValue",
    "true": "trueValue",
    "false": "falseValue",
}


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    camel = head + "".join(p.title() for p in rest)
    return DART_RESERVED.get(camel, camel)


def to_dart(tokens: dict[str, Any]) -> str:
    lines = [
        "// %s" % BANNER,
        "// %s" % REGENERATE,
        "//",
        "// Product brief 6.1: the core palette is six values and the pen set is",
        "// used ONLY inside the 3D canvas and for annotation. A pen colour on",
        "// chrome is a bug, and so is a Color literal anywhere else in the app.",
        "",
        "import 'dart:ui';",
        "",
        "/// The machine's own colours.",
        "class BpCore {",
        "  BpCore._();",
        "",
    ]
    for name, value in _clean(tokens["core"]).items():
        lines.append("  /// %s" % value["use"])
        lines.append("  static const Color %s = %s;"
                     % (_camel(name), _dart_colour(value["hex"])))
        lines.append("")
    lines.append("}")
    lines.append("")

    lines += [
        "/// Plotter pens. Canvas and annotation only, and every one is paired",
        "/// with an icon or a label - brief 6.7 forbids colour-only status.",
        "class BpPen {",
        "  BpPen._();",
        "",
    ]
    for name, value in _clean(tokens["pen"]).items():
        lines.append("  /// %s" % value["meaning"])
        lines.append("  static const Color %s = %s;"
                     % (_camel(name), _dart_colour(value["hex"])))
        lines.append("")
    lines.append("}")
    lines.append("")

    mono = tokens["type"]["mono"]["stack"].split(",")[0].strip().strip("'\"")
    prose = tokens["type"]["prose"]["stack"].split(",")[0].strip().strip("'\"")
    lines += [
        "/// Two families, and the scale they are set at.",
        "class BpType {",
        "  BpType._();",
        "",
        "  /// %s" % tokens["type"]["mono"]["use"],
        "  static const String mono = '%s';" % mono,
        "",
        "  /// %s" % tokens["type"]["prose"]["use"],
        "  static const String prose = '%s';" % prose,
        "",
    ]
    for name, size in _clean(tokens["type"]["scale"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("")
    for name, weight in _clean(tokens["type"]["weight"]).items():
        lines.append("  static const int weight%s = %d;"
                     % (name.title(), weight))
    lines.append("}")
    lines.append("")

    lines += ["/// A 4-based scale. Every gap in the app is one of these.",
              "class BpSpace {", "  BpSpace._();", ""]
    for name, size in _clean(tokens["space"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("}")
    lines.append("")

    lines += ["/// Squared-off rather than pill-shaped: a machine, not a toy.",
              "class BpRadius {", "  BpRadius._();", ""]
    for name, size in _clean(tokens["radius"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("}")
    lines.append("")

    lines += ["/// Constants the brief pins, so neither client invents one.",
              "class BpMetric {", "  BpMetric._();", ""]
    for name, size in _clean(tokens["metric"]).items():
        lines.append("  static const double %s = %g;" % (_camel(name), size))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--check", action="store_true",
                        help="fail if an export is stale; write nothing")
    args = parser.parse_args(argv)

    tokens = load()
    wanted = {CSS_OUT: to_css(tokens), DART_OUT: to_dart(tokens)}

    if args.check:
        stale = [
            path for path, text in wanted.items()
            if not path.is_file() or path.read_text() != text
        ]
        if stale:
            print("stale token exports:")
            for path in stale:
                print("  %s" % path.relative_to(ROOT))
            print("\nrun: python tools/tokens.py")
            return 1
        print("token exports are current")
        return 0

    for path, text in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print("wrote %s" % path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
