// GENERATED FROM design/tokens.json - DO NOT EDIT THIS FILE
// Change the token there and run: python tools/tokens.py
//
// Product brief 6.1: the core palette is six values and the pen set is
// used ONLY inside the 3D canvas and for annotation. A pen colour on
// chrome is a bug, and so is a Color literal anywhere else in the app.

import 'dart:ui';

/// The machine's own colours.
class BpCore {
  BpCore._();

  /// app background, the machine's shell
  static const Color caseColor = Color(0xFF0B0F0D);

  /// panels, cards, raised surfaces
  static const Color bezel = Color(0xFF151B18);

  /// rules, borders, grid lines, inactive strokes
  static const Color etch = Color(0xFF2A322D);

  /// primary accent, active state, primary actions, focused input
  static const Color phosphor = Color(0xFFFFB000);

  /// primary text
  static const Color screen = Color(0xFFDCE3DC);

  /// secondary text, labels, disabled
  static const Color dim = Color(0xFF7C8880);

}

/// Plotter pens. Canvas and annotation only, and every one is paired
/// with an icon or a label - brief 6.7 forbids colour-only status.
class BpPen {
  BpPen._();

  /// the printable part
  static const Color solid = Color(0xFFDCE3DC);

  /// grid, graticule, construction geometry
  static const Color dim = Color(0xFF4A554E);

  /// reference body from a photo, never printed
  static const Color ref = Color(0xFF35C6E8);

  /// passed check, confirmed dimension, joint clearance OK
  static const Color pass = Color(0xFF5BE37D);

  /// tolerance risk, uncalibrated default, thin wall
  static const Color warn = Color(0xFFFFB000);

  /// failed check, interpenetration, out of bed bounds
  static const Color fail = Color(0xFFE8489B);

}

/// Two families, and the scale they are set at.
class BpType {
  BpType._();

  /// labels, parameters, numbers, dimensions, the command line, the coordinate readout, buttons
  static const String mono = 'IBM Plex Mono';

  /// anything longer than two lines
  static const String prose = 'Inter';

  static const double micro = 10.5;
  static const double label = 12;
  static const double body = 13.5;
  static const double reading = 15;
  static const double figure = 17;
  static const double title = 21;
  static const double display = 27;

  static const int weightRegular = 400;
  static const int weightMedium = 500;
  static const int weightBold = 600;
}

/// A 4-based scale. Every gap in the app is one of these.
class BpSpace {
  BpSpace._();

  static const double hair = 2;
  static const double tight = 4;
  static const double snug = 8;
  static const double base = 12;
  static const double wide = 16;
  static const double loose = 24;
  static const double room = 32;
  static const double hall = 48;
}

/// Squared-off rather than pill-shaped: a machine, not a toy.
class BpRadius {
  BpRadius._();

  static const double none = 0;
  static const double edge = 3;
  static const double panel = 6;
  static const double card = 10;
}

/// Constants the brief pins, so neither client invents one.
class BpMetric {
  BpMetric._();

  static const double tap = 44;
  static const double minWidth = 380;
}
